# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-LaDBI
version:      1.1.0
version_from: lib/POE/Component/LaDBI.pm
installdirs:  site
requires:
    DBI:                           1.20
    POE:                           0.18

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
